### ISSUE TITLE
class diagram của ngọc

### ISSUE THREAD

**Issue by daibangdangcap** [daibangdangcap/PTTKPM_N7_DULICH#9]
làm xong gửi file .mdj vào đây

**Comment by peongox** [comment]
[NVQuanLyTour.zip](https://github.com/daibangdangcap/PTTKPM_N7_DULICH/files/11358588/NVQuanLyTour.zip)

**Comment by peongox** [comment]
![image](https://user-images.githubusercontent.com/130962428/235289053-6b101dba-8287-4116-8aea-5481c1acacbe.png)

/ảnh xem trước/
